//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextWebServiceClient2.TextWS2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextWS2.TextWebServiceSoap")]
    public interface TextWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name parm1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toUpper", ReplyAction="*")]
        TextWebServiceClient2.TextWS2.toUpperResponse toUpper(TextWebServiceClient2.TextWS2.toUpperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toUpper", ReplyAction="*")]
        System.Threading.Tasks.Task<TextWebServiceClient2.TextWS2.toUpperResponse> toUpperAsync(TextWebServiceClient2.TextWS2.toUpperRequest request);
        
        // CODEGEN: Generating message contract since element name parm1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toLower", ReplyAction="*")]
        TextWebServiceClient2.TextWS2.toLowerResponse toLower(TextWebServiceClient2.TextWS2.toLowerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/toLower", ReplyAction="*")]
        System.Threading.Tasks.Task<TextWebServiceClient2.TextWS2.toLowerResponse> toLowerAsync(TextWebServiceClient2.TextWS2.toLowerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toUpperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toUpper", Namespace="http://tempuri.org/", Order=0)]
        public TextWebServiceClient2.TextWS2.toUpperRequestBody Body;
        
        public toUpperRequest() {
        }
        
        public toUpperRequest(TextWebServiceClient2.TextWS2.toUpperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toUpperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parm1;
        
        public toUpperRequestBody() {
        }
        
        public toUpperRequestBody(string parm1) {
            this.parm1 = parm1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toUpperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toUpperResponse", Namespace="http://tempuri.org/", Order=0)]
        public TextWebServiceClient2.TextWS2.toUpperResponseBody Body;
        
        public toUpperResponse() {
        }
        
        public toUpperResponse(TextWebServiceClient2.TextWS2.toUpperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toUpperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toUpperResult;
        
        public toUpperResponseBody() {
        }
        
        public toUpperResponseBody(string toUpperResult) {
            this.toUpperResult = toUpperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toLowerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toLower", Namespace="http://tempuri.org/", Order=0)]
        public TextWebServiceClient2.TextWS2.toLowerRequestBody Body;
        
        public toLowerRequest() {
        }
        
        public toLowerRequest(TextWebServiceClient2.TextWS2.toLowerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toLowerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parm1;
        
        public toLowerRequestBody() {
        }
        
        public toLowerRequestBody(string parm1) {
            this.parm1 = parm1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toLowerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="toLowerResponse", Namespace="http://tempuri.org/", Order=0)]
        public TextWebServiceClient2.TextWS2.toLowerResponseBody Body;
        
        public toLowerResponse() {
        }
        
        public toLowerResponse(TextWebServiceClient2.TextWS2.toLowerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class toLowerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toLowerResult;
        
        public toLowerResponseBody() {
        }
        
        public toLowerResponseBody(string toLowerResult) {
            this.toLowerResult = toLowerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextWebServiceSoapChannel : TextWebServiceClient2.TextWS2.TextWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextWebServiceSoapClient : System.ServiceModel.ClientBase<TextWebServiceClient2.TextWS2.TextWebServiceSoap>, TextWebServiceClient2.TextWS2.TextWebServiceSoap {
        
        public TextWebServiceSoapClient() {
        }
        
        public TextWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextWebServiceClient2.TextWS2.toUpperResponse TextWebServiceClient2.TextWS2.TextWebServiceSoap.toUpper(TextWebServiceClient2.TextWS2.toUpperRequest request) {
            return base.Channel.toUpper(request);
        }
        
        public string toUpper(string parm1) {
            TextWebServiceClient2.TextWS2.toUpperRequest inValue = new TextWebServiceClient2.TextWS2.toUpperRequest();
            inValue.Body = new TextWebServiceClient2.TextWS2.toUpperRequestBody();
            inValue.Body.parm1 = parm1;
            TextWebServiceClient2.TextWS2.toUpperResponse retVal = ((TextWebServiceClient2.TextWS2.TextWebServiceSoap)(this)).toUpper(inValue);
            return retVal.Body.toUpperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextWebServiceClient2.TextWS2.toUpperResponse> TextWebServiceClient2.TextWS2.TextWebServiceSoap.toUpperAsync(TextWebServiceClient2.TextWS2.toUpperRequest request) {
            return base.Channel.toUpperAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextWebServiceClient2.TextWS2.toUpperResponse> toUpperAsync(string parm1) {
            TextWebServiceClient2.TextWS2.toUpperRequest inValue = new TextWebServiceClient2.TextWS2.toUpperRequest();
            inValue.Body = new TextWebServiceClient2.TextWS2.toUpperRequestBody();
            inValue.Body.parm1 = parm1;
            return ((TextWebServiceClient2.TextWS2.TextWebServiceSoap)(this)).toUpperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextWebServiceClient2.TextWS2.toLowerResponse TextWebServiceClient2.TextWS2.TextWebServiceSoap.toLower(TextWebServiceClient2.TextWS2.toLowerRequest request) {
            return base.Channel.toLower(request);
        }
        
        public string toLower(string parm1) {
            TextWebServiceClient2.TextWS2.toLowerRequest inValue = new TextWebServiceClient2.TextWS2.toLowerRequest();
            inValue.Body = new TextWebServiceClient2.TextWS2.toLowerRequestBody();
            inValue.Body.parm1 = parm1;
            TextWebServiceClient2.TextWS2.toLowerResponse retVal = ((TextWebServiceClient2.TextWS2.TextWebServiceSoap)(this)).toLower(inValue);
            return retVal.Body.toLowerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextWebServiceClient2.TextWS2.toLowerResponse> TextWebServiceClient2.TextWS2.TextWebServiceSoap.toLowerAsync(TextWebServiceClient2.TextWS2.toLowerRequest request) {
            return base.Channel.toLowerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextWebServiceClient2.TextWS2.toLowerResponse> toLowerAsync(string parm1) {
            TextWebServiceClient2.TextWS2.toLowerRequest inValue = new TextWebServiceClient2.TextWS2.toLowerRequest();
            inValue.Body = new TextWebServiceClient2.TextWS2.toLowerRequestBody();
            inValue.Body.parm1 = parm1;
            return ((TextWebServiceClient2.TextWS2.TextWebServiceSoap)(this)).toLowerAsync(inValue);
        }
    }
}
